project:
  type: website
  output-dir: docs

website:
  title: "William Farin - Data Scientist / Biostatisticien"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - href: survival_analysis.qmd
        text: Survival Analysis
      - href: classification_blood_cells_cnn.qmd
        text: Classification of blood cells with CNN
      - href: mon-cv.qmd
        text: mon cv
      - about.qmd
      
    right:
      - icon: github
        href: https://github.com/wfarin
      - icon: linkedin
        href: https://linkedin.com/in/ton-profil

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

